### ISSUE TITLE
Add a player to track editing

### ISSUE THREAD

**Issue by Thiagobhmg** [avivharuzi/subtitles-online-editor#13]
congratulations on the project.

It would be nice to put a player to accompany the edit. for both Videos and Audios. It would let the player upload video and audios to the cloud as well, .m3u8/mp3/mp4 files

When adding the player, place a button with play on each line that, when activated, plays the media with the caption exactly at the time the button was activated.

**Comment by avivharuzi** [comment]
It's a good a very good idea!
But this project was built for more simple editing.
Maybe I will do something in the future 😄
